#!/usr/bin/env python
"""Build the lead figure (successor of fig-a09699c2f95b).

Per-dataset panels of test accuracy vs compute (FLOPs x-axis, linear,
per-panel scale; wall-clock variant for the appendix via --x wall). Markers:

* per-seed recipe runs — open circles;
* one star per fixed k in {2, 3, 6} — mean +/- sd across seeds, each a TRUE
  one-run recipe (no hidden best-of-k; the k-selected variant is priced at
  ~3-4 runs and lives in paper text only);
* the TopoBench menu — ONE square at its true cost, with symmetric
  per-seed-selection error bars (per-seed validation-best selection, not
  pooled-val-best);
* ceilings — dotted dark: exact 6-space optimum; light gray: best-known
  11-space lower bound.

Inputs (data/frozen/): the #14 marker-arm checkpoint (per-seed masks, test
accuracy, inline FLOPs, plain + anchored selectors), menu12-derived per-seed
menu selection, and landscape ceilings. Until ingestion, --demo renders
synthetic data with a DEMO watermark so the pipeline stays exercised.

Usage:
    python figures/build_lead_figure.py --demo
    python figures/build_lead_figure.py --selector anchored --x flops
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import style  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
OUT_DIR = REPO / "figures" / "out"

DATASETS_DEFAULT = [
    "benzene",
    "fluoride_carbonyl",
    "mutagenicity_gxai",
    "NCI1",
    "MUTAG",
    "NCI109",
    "alkane_carbonyl",
    "cocitation_cora",
    "cocitation_citeseer",
    "cocitation_pubmed",
    "mantra_orientation",
]

#: canonical result-file keys -> panel display titles
DISPLAY = {
    "benzene": "Benzene",
    "fluoride_carbonyl": "Fluoride-Carbonyl",
    "mutagenicity_gxai": "Mutagenicity",
    "NCI1": "NCI1",
    "MUTAG": "MUTAG",
    "NCI109": "NCI109",
    "alkane_carbonyl": "Alkane-Carbonyl",
    "cocitation_cora": "Cora",
    "cocitation_citeseer": "Citeseer",
    "cocitation_pubmed": "Pubmed",
    "mantra_orientation": "MANTRA (balanced)",
}

#: datasets whose honest y-metric is balanced accuracy (class imbalance);
#: rows lacking the balanced column are dropped from those panels.
BALANCED_DATASETS = {"mantra_orientation"}


def _with_yval(df: pd.DataFrame) -> pd.DataFrame:
    """Add the per-row plotting metric: balanced accuracy on imbalanced
    datasets (dropping rows that lack it), plain test accuracy elsewhere."""
    if df is None or df.empty:
        return df
    df = df.copy()
    bal = df.get("test_balanced_accuracy")
    is_bal = df.dataset.isin(BALANCED_DATASETS)
    df["yval"] = df.test_accuracy.where(
        ~is_bal, bal if bal is not None else float("nan")
    )
    return df.dropna(subset=["yval"])


def _concat_frames(*paths: str) -> pd.DataFrame | None:
    frames = []
    for p in paths:
        f = REPO / "data" / "frozen" / p
        if f.exists():
            frames.append(pd.read_parquet(f))
    if not frames:
        return None
    return pd.concat(frames, ignore_index=True)


# --------------------------------------------------------------------------
# data contracts
# --------------------------------------------------------------------------
# recipe frame: dataset, seed, selector, k, mask, test_accuracy, flops
# menu frame:   dataset, seed, test_accuracy, flops   (per-seed val-best pick)
# ceilings:     dataset -> {"exact6": float | None, "best11": float | None}


def load_frozen(selector: str):
    from toposhap.io import load_marker_arm14

    try:
        # canonical n=3 measurement-exact arms (researcher directive
        # 2026-08-17), all dataset batches merged; #14 frame is the fallback
        df = _concat_frames("anchored3_exact.parquet",
                            "anchored3_exact_t1.parquet",
                            "anchored3_exact_mantra.parquet")
        if df is not None:
            df["selector"] = "anchored"
        elif (REPO / "data" / "frozen"
              / "marker_arm14_frame.parquet").exists():
            df = pd.read_parquet(REPO / "data" / "frozen"
                                 / "marker_arm14_frame.parquet")
        else:
            df = load_marker_arm14()
    except FileNotFoundError:
        # pre-#14 fallback: the #12 recipe frame (3 seeds, plain selector,
        # wall-clock only) generated by scripts/make_tables.py --recipe12
        fallback = REPO / "data" / "frozen" / "recipe12.parquet"
        if not fallback.exists() or selector != "plain":
            raise
        print("NOTE: marker_arm14 not ingested — falling back to recipe12 "
              "(#12 data, plain selector, wall-clock axis only)")
        df = pd.read_parquet(fallback)
    required = {"dataset", "seed", "selector", "k", "test_accuracy", "flops"}
    missing = required - set(df.columns)
    if missing:
        raise KeyError(
            f"marker-arm frame lacks columns {sorted(missing)} — reconcile "
            "the checkpoint schema in toposhap/io/results.py before plotting"
        )
    recipe = df[df.selector == selector].copy()

    menu_path = REPO / "data" / "frozen" / "menu_per_seed_selection.parquet"
    if not menu_path.exists():
        raise FileNotFoundError(
            f"{menu_path} missing — generate with scripts/make_tables.py "
            "--menu-per-seed from menu12.json"
        )
    menu = pd.read_parquet(menu_path)

    ceil_path = REPO / "data" / "frozen" / "ceilings.parquet"
    ceilings = {}
    if ceil_path.exists():
        cdf = pd.read_parquet(ceil_path)
        for _, row in cdf.iterrows():
            ceilings[row.dataset] = {
                "exact6": row.get("exact6"),
                "best11": row.get("best11"),
            }

    # real auto-k marker (backward elimination, local arm) if generated;
    # falls back to nothing — the phi-sizing preview is opt-in via CLI only
    autok_path = REPO / "data" / "frozen" / "autok_marker.parquet"
    autok = pd.read_parquet(autok_path) if autok_path.exists() else None

    base_path = REPO / "data" / "frozen" / "baseline_markers.parquet"
    baselines = pd.read_parquet(base_path) if base_path.exists() else None
    extra = []
    for pq in ("hopse_sweep_t1.parquet", "hopse_sweep_mantra.parquet",
           "hopse_sweep_citations.parquet"):
        sw = _concat_frames(pq)
        if sw is None:
            continue
        key = "subset_identity" if "subset_identity" in sw.columns else "mask"
        for ds2, sub in sw.groupby("dataset"):
            grid_flops = float(sub.groupby(key).flops.mean().sum())
            for seed, g in sub.groupby("seed"):
                best = g.loc[g.val_accuracy.idxmax()]
                extra.append(dict(
                    dataset=ds2, baseline="hopse_best",
                    n_configs=sub[key].nunique(), flops=grid_flops,
                    wall_seconds=float("nan"), flops_estimated=False,
                    seed=int(seed),
                    test_accuracy=float(best.test_accuracy),
                    val_accuracy=float(best.val_accuracy),
                    test_balanced_accuracy=float(
                        best.get("test_balanced_accuracy", float("nan"))),
                    winner=str(best.get(key, ""))))
    if extra:
        baselines = pd.concat(
            [baselines, pd.DataFrame(extra)], ignore_index=True
        ) if baselines is not None else pd.DataFrame(extra)
    return recipe, menu, ceilings, False, autok, baselines


def demo_frames(seed: int = 0):
    """Synthetic data shaped like the real thing (watermarked at render)."""
    rng = np.random.default_rng(seed)
    recipes, menus, ceilings = [], [], {}
    for d_i, ds in enumerate(DATASETS_DEFAULT):
        base = 0.72 + 0.05 * rng.random()
        unit = 10 ** (14 + d_i % 3)  # per-panel FLOPs scale
        for k, acc_k in [(2, -0.01), (3, 0.005), (6, 0.012)]:
            for s in range(5):
                recipes.append(
                    dict(
                        dataset=ds,
                        seed=42 + s,
                        selector="anchored",
                        k=k,
                        mask=21,
                        test_accuracy=base
                        + acc_k
                        + rng.normal(0, 0.008),
                        flops=unit * (1.2 + 0.1 * k + rng.normal(0, 0.05)),
                    )
                )
        for s in range(5):
            menus.append(
                dict(
                    dataset=ds,
                    seed=42 + s,
                    test_accuracy=base + 0.01 + rng.normal(0, 0.006),
                    flops=unit * 6.0 * (1 + rng.normal(0, 0.03)),
                )
            )
        ceilings[ds] = {"exact6": base + 0.035, "best11": base + 0.05}
    return (
        pd.DataFrame(recipes),
        pd.DataFrame(menus),
        ceilings,
        True,
    )


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------


#: sweep-best baselines: (marker, color, legend label) — PALE: they are the
#: reference points; our markers carry the dark colors.
BASELINE_STYLE = {
    "hopse_best": ("<", "#9fcfd0", "HOPSE sweep best (12 cfg)"),
    "gccn_sweep_best": (">", "#d9b992", "GCCN sweep best (~23 cfg)"),
    "originals_best": ("X", "#e5aab2", "TDL originals best (4 arch)"),
}


def build(recipe: pd.DataFrame, menu: pd.DataFrame, ceilings: dict,
          demo: bool, xcol: str = "flops", selector: str = "anchored",
          only: list | None = None, stem_name: str | None = None,
          out_stem: str = "lead_figure", autok: pd.DataFrame | None = None,
          baselines: pd.DataFrame | None = None,
          hide: set[str] | None = None,
          rows: list | None = None) -> Path:
    hide = hide or set()  # subset of {menu, k2, k3, k6, ladder1, ladder2}
    style.apply()
    recipe = _with_yval(recipe)
    menu = _with_yval(menu)
    autok = _with_yval(autok) if autok is not None else None
    baselines = _with_yval(baselines) if baselines is not None else None
    if rows:
        pool = [d for row in rows for d in row]
    else:
        pool = only if only else DATASETS_DEFAULT
    datasets = [d for d in pool if d in set(recipe.dataset)] or (
        sorted(set(recipe.dataset))
    )
    n = len(datasets)
    if rows:
        present = set(datasets)
        placement = [(r, c)
                     for r, row in enumerate(rows)
                     for c, d in enumerate([x for x in row if x in present])]
        nrows = len(rows)
        ncols = max(len([x for x in row if x in present]) for row in rows)
    else:
        nrows = 2 if n > 7 else 1
        ncols = -(-n // nrows)
        placement = [(i // ncols, i % ncols) for i in range(n)]
    # 2 subcolumns per panel so a short row can be centered by a
    # half-panel offset
    from collections import Counter
    row_len = Counter(r for r, _ in placement)
    fig = plt.figure(figsize=(3.3 * ncols, 3.0 * nrows))
    gs = fig.add_gridspec(nrows, 2 * ncols, hspace=0.42, wspace=0.62)
    axes_by_pos = {}
    for r, c in placement:
        off = ncols - row_len[r]  # half-panel units
        axes_by_pos[(r, c)] = fig.add_subplot(
            gs[r, 2 * c + off:2 * c + off + 2])
    axes = [axes_by_pos[pos] for pos in placement]

    # uniform y-span across panels (hard requirement)
    panel_ranges = []
    for ds in datasets:
        ys = list(recipe[recipe.dataset == ds].yval) + list(
            menu[menu.dataset == ds].yval
        )
        if baselines is not None:
            ys += list(baselines[baselines.dataset == ds].yval)
        c = ceilings.get(ds, {})
        ys += [v for v in (c.get("exact6"), c.get("best11")) if v]
        panel_ranges.append((min(ys), max(ys)))
    plain_idx = [i for i, d in enumerate(datasets)
                 if d not in BALANCED_DATASETS]
    bal_idx = [i for i, d in enumerate(datasets) if d in BALANCED_DATASETS]
    ylims = [None] * len(datasets)
    for group in (plain_idx, bal_idx):
        if group:
            for i, lim in zip(group, style.uniform_yspan(
                    [panel_ranges[i] for i in group])):
                ylims[i] = lim

    for ax, ds, ylim in zip(axes, datasets, ylims):
        r = recipe[recipe.dataset == ds]
        m = menu[menu.dataset == ds]

        c = ceilings.get(ds, {})
        if "ceiling" not in hide:
            if c.get("exact6") is not None:
                ax.axhline(c["exact6"], ls=":", lw=1.2, color=style.DARK,
                           zorder=1)
            if c.get("best11") is not None:
                ax.axhline(c["best11"], ls="-", lw=1.0,
                           color=style.GRAY_LIGHT, zorder=1)

        # per-seed dots: open circles (hide with "seeds")
        if "seeds" not in hide:
            ax.scatter(r[xcol], r.yval, s=style.DOT_SIZE,
                       facecolors="none", edgecolors=style.SEED_DOT,
                       lw=0.8, zorder=2)

        # one star per fixed k, error bars on every marker
        for k, (marker, color, label) in style.STAR_BY_K.items():
            if f"k{k}" in hide:
                continue
            rk = r[r.k == k]
            if rk.empty:
                continue
            x, y = rk[xcol].mean(), rk.yval.mean()
            ysd = rk.yval.std(ddof=1)
            ax.errorbar(x, y, yerr=ysd, fmt="none", ecolor=color,
                        elinewidth=1.2, capsize=2.5, zorder=3)
            ax.scatter([x], [y], marker=marker, s=style.STAR_SIZE, color=color,
                       zorder=4, label=label if ds == datasets[0] else None)

        # auto-k preview: self-sized k via leftover-phi < binomial-se
        # (n limited to seeds with cheap games in the snapshot; see caption)
        if "ladder1" in hide:
            autok = None
        if autok is not None:
            a = autok[autok.dataset == ds].dropna(subset=[xcol])
            if not a.empty:
                x, y = a[xcol].mean(), a.yval.mean()
                ysd = a.yval.std(ddof=1) if len(a) > 1 else 0.0
                ax.errorbar(x, y, yerr=ysd, fmt="none", ecolor="#7b2d8b",
                            elinewidth=1.2, capsize=2.5, zorder=3)
                ax.scatter([x], [y], marker="p", s=90, color="#7b2d8b",
                           zorder=5,
                           label=f"OURS selection B=1 (exploratory, n={len(a)})"
                           if ds == datasets[0] else None)

        # ladder B=2 (two trained rungs, val-selected), all batches merged
        b2 = _with_yval(_concat_frames("ladder_b2_marker.parquet",
                                       "ladder_b2_t1.parquet",
                                       "ladder_b2_mantra.parquet"))
        if b2 is not None and "ladder2" not in hide:
            b = b2[b2.dataset == ds].dropna(subset=[xcol])
            if not b.empty:
                x, y = b[xcol].mean(), b.yval.mean()
                ysd = b.yval.std(ddof=1) if len(b) > 1 else 0.0
                ax.errorbar(x, y, yerr=ysd, fmt="none", ecolor="#1b5e20",
                            elinewidth=1.3, capsize=2.5, zorder=3)
                ax.scatter([x], [y], marker="h", s=100, color="#1b5e20",
                           zorder=5,
                           label="OURS (GCCN)"
                           if ds == datasets[0] else None)

        # the canonical ladder B=2 arm in HOPSE's encoding space (identical
        # pipeline to the GCCN ladder; #13's fixed-k arm retired to appendix)
        oh = _with_yval(_concat_frames("ladder_b2_hopse.parquet",
                                       "ladder_b2_hopse_t1.parquet",
                                       "ladder_b2_hopse_mantra.parquet"))
        if oh is not None and "ours_hopse" not in hide:
            o = oh[oh.dataset == ds].dropna(subset=[xcol])
            if not o.empty:
                x, y = o[xcol].mean(), o.yval.mean()
                ysd = o.yval.std(ddof=1) if len(o) > 1 else 0.0
                ax.errorbar(x, y, yerr=ysd, fmt="none", ecolor="#075e63",
                            elinewidth=1.3, capsize=2.5, zorder=3)
                ax.scatter([x], [y], marker="^", s=100, color="#075e63",
                           zorder=5,
                           label="OURS (HOPSE)"
                           if ds == datasets[0] else None)

        # OURS fixed size k=3 (ladder rung) in the HOPSE family — the
        # rule-free counterpart of the GCCN anchored star
        k3 = _with_yval(_concat_frames("hopse_k3_rung.parquet"))
        if k3 is not None and "hopse_k3" not in hide:
            kk = k3[k3.dataset == ds].dropna(subset=[xcol])
            if not kk.empty:
                x, y = kk[xcol].mean(), kk.yval.mean()
                ysd = kk.yval.std(ddof=1) if len(kk) > 1 else 0.0
                ax.errorbar(x, y, yerr=ysd, fmt="none", ecolor="#075e63",
                            elinewidth=1.2, capsize=2.5, zorder=3)
                ax.scatter([x], [y], marker="*", s=130, color="#075e63",
                           zorder=5,
                           label="OURS fixed k=3 (HOPSE)"
                           if ds == datasets[0] else None)

        # sweep-best baselines at the SWEEP's cost (budget-matching rule)
        if baselines is not None:
            for bl, (mk, col, lab) in BASELINE_STYLE.items():
                b = baselines[(baselines.dataset == ds)
                              & (baselines.baseline == bl)].dropna(
                                  subset=[xcol])
                if b.empty:
                    continue
                x, y = b[xcol].mean(), b.yval.mean()
                ysd = b.yval.std(ddof=1) if len(b) > 1 else 0.0
                ax.errorbar(x, y, yerr=ysd, fmt="none", ecolor=col,
                            elinewidth=1.1, capsize=2.5, zorder=3)
                ax.scatter([x], [y], marker=mk, s=70, color=col, zorder=4,
                           label=lab if ds == datasets[0] else None)

        # menu: one square, symmetric per-seed-selection bars
        if not m.empty and "menu" not in hide:
            x, y = m[xcol].mean(), m.yval.mean()
            ysd = m.yval.std(ddof=1)
            ax.errorbar(x, y, yerr=ysd, fmt="none", ecolor=style.MENU_SQUARE,
                        elinewidth=1.2, capsize=2.5, zorder=3)
            ax.scatter([x], [y], marker="s", s=style.SQUARE_SIZE,
                       color=style.MENU_SQUARE, zorder=4,
                       label="menu (val-best of 6)" if ds == datasets[0]
                       else None)

        ax.set_ylim(*ylim)
        ax.set_title(DISPLAY.get(ds, ds), fontsize=13)
        ax.set_xlabel("FLOPs" if xcol == "flops" else "wall-clock (s)",
                      fontsize=12)
        ax.tick_params(labelsize=10.5)
        # linear axes are a hard requirement — never set log scales here
        assert ax.get_xscale() == "linear" and ax.get_yscale() == "linear"
        ax.ticklabel_format(axis="x", style="sci", scilimits=(0, 0))
        ax.xaxis.get_offset_text().set_fontsize(9.5)

    for r0 in range(nrows):
        axes_by_pos[(r0, 0)].set_ylabel("test accuracy", fontsize=12)
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", ncol=len(labels),
               fontsize=12,
               bbox_to_anchor=(0.5, 1.14 if nrows == 1 else 1.04))

    if demo:
        fig.text(0.5, 0.5, "DEMO DATA — NOT RESULTS", fontsize=28,
                 color="red", alpha=0.25, ha="center", va="center",
                 rotation=12)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    suffix = "_demo" if demo else ""
    if xcol != "flops":
        suffix += f"_{xcol}"
    if stem_name:
        out_stem = stem_name
    pdf = OUT_DIR / f"{out_stem}_{selector}{suffix}.pdf"
    fig.savefig(pdf, bbox_inches="tight")
    fig.savefig(pdf.with_suffix(".png"), dpi=170,
                bbox_inches="tight")
    plt.close(fig)
    return pdf


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--demo", action="store_true",
                    help="render synthetic, watermarked data")
    ap.add_argument("--selector", default="anchored",
                    choices=["anchored", "plain"])
    ap.add_argument("--x", dest="xcol", default="flops",
                    choices=["flops", "wall_seconds"])
    ap.add_argument("--with-autok-preview", action="store_true",
                    help="overlay the phi-sizing auto-k stand-in (NOT the "
                    "pre-registered greedy rule; n=2 seeds; off by default)")
    ap.add_argument("--hide", default="",
                    help="comma list of markers to omit: "
                    "menu,k2,k3,k6,ladder1,ladder2")
    args = ap.parse_args()

    if args.demo:
        recipe, menu, ceilings, demo = demo_frames()
        autok = baselines = None
    else:
        recipe, menu, ceilings, demo, autok, baselines = load_frozen(
            args.selector)
        if autok is not None and "selector" in autok.columns:
            autok = autok[autok.selector == "autok_backward"]
    hide = {h.strip() for h in args.hide.split(",") if h.strip()}
    pdf = build(recipe, menu, ceilings, demo, xcol=args.xcol,
                selector=args.selector, autok=autok, baselines=baselines,
                hide=hide)
    print(f"wrote {pdf} (+.png)")
    # the paper includes figures/out/lead_figure.pdf — keep the canonical
    # render (anchored, FLOPs, real data) aliased to that name
    if not demo and args.selector == "anchored" and args.xcol == "flops":
        import shutil

        # headline (decluttered) render vs complete-marker appendix render
        alias = "lead_figure" if hide else "lead_figure_full"
        for ext in (".pdf", ".png"):
            shutil.copyfile(pdf.with_suffix(ext),
                            pdf.parent / f"{alias}{ext}")
        print(f"aliased -> {pdf.parent / (alias + '.pdf')}")
    if not demo and args.selector == "anchored" and args.xcol == "wall_seconds":
        import shutil

        for ext in (".pdf", ".png"):
            shutil.copyfile(pdf.with_suffix(ext),
                            pdf.parent / f"lead_figure_wall{ext}")
        print(f"aliased -> {pdf.parent / 'lead_figure_wall.pdf'}")


if __name__ == "__main__":
    main()
