#!/usr/bin/env python
"""Assemble overleaf_export/: a self-contained folder to upload to an
ICLR 2027 Overleaf project.

    python scripts/make_overleaf_export.py

Contents: main.tex, preamble.tex, results_macros.tex, references.bib,
the (placeholder) iclr2027_conference.sty, sections/, tables/, and
figures/ holding exactly the PDFs the text references, with
``../figures/out/`` paths rewritten to ``figures/``. Missing figures
are reported (the \\figureplaceholder fallback keeps the build green).
Re-run after any regeneration pass; the folder is fully overwritten.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PAPER = REPO / "paper"
DEST = REPO / "overleaf_export"

FIG_RE = re.compile(r"\.\./figures/out/([A-Za-z0-9_]+\.(?:pdf|png))")

#: the repo-internal draft machinery, resolved away so the uploaded
#: source reads like a normal paper (results are frozen, so \unfrozen
#: renders its argument plainly anyway)
UNFROZEN_RE = re.compile(r"\\unfrozen\{([^{}]*)\}")
IFFILE_RE = re.compile(
    r"\\IfFileExists\{[^}]*\}\{%\s*\n\s*"
    r"(\\includegraphics\[[^]]*\]\{[^}]*\})%\s*\n\s*\}\{%\s*\n\s*"
    r"\\figureplaceholder\{[^}]*\}%\s*\n\s*\}")
FROZEN_BLOCK_RE = re.compile(
    r"% ----- frozen-results toggle -+\n.*?\\fi\}\n", re.S)


def rewrite(text: str) -> str:
    text = text.replace("../figures/out/", "figures/")
    text = UNFROZEN_RE.sub(r"\1", text)
    text = IFFILE_RE.sub(r"\1", text)
    return text


def main() -> None:
    if DEST.exists():
        shutil.rmtree(DEST)
    (DEST / "sections").mkdir(parents=True)
    (DEST / "tables").mkdir()
    (DEST / "figures").mkdir()

    figures: set[str] = set()
    for name in ("main.tex", "preamble.tex", "results_macros.tex"):
        text = (PAPER / name).read_text()
        figures.update(FIG_RE.findall(text))
        if name == "preamble.tex":
            text = FROZEN_BLOCK_RE.sub("", text)
        if name == "results_macros.tex":
            head_end = text.index("% " + "=" * 70, 10)
            text = ("% results_macros.tex -- every result number in the "
                    "paper, generated\n% from the frozen experimental "
                    "record. Do not edit numbers by hand.\n"
                    + text[head_end:])
            text = text.replace("UNFROZEN", "generated")
        (DEST / name).write_text(rewrite(text))
    for f in sorted((PAPER / "sections").glob("*.tex")):
        if f.name == "07_trustworthiness.tex":  # removed from main.tex
            continue
        text = f.read_text()
        figures.update(FIG_RE.findall(text))
        (DEST / "sections" / f.name).write_text(rewrite(text))
    wanted = set()
    for f in [PAPER / "main.tex", *(PAPER / "sections").glob("*.tex")]:
        stripped = re.sub(r"(?<!\\)%.*", "", f.read_text())
        wanted.update(re.findall(r"\\input\{tables/([^}]+)\}", stripped))
    for name in sorted(wanted):
        f = PAPER / "tables" / f"{name}.tex"
        if f.exists():
            (DEST / "tables" / f.name).write_text(rewrite(f.read_text()))
    shutil.copy(PAPER / "references.bib", DEST / "references.bib")
    shutil.copy(PAPER / "iclr2027_conference.sty",
                DEST / "iclr2027_conference.sty")

    missing = []
    for name in sorted(figures):
        src = REPO / "figures" / "out" / name
        if src.exists():
            shutil.copy(src, DEST / "figures" / name)
        else:
            missing.append(name)

    (DEST / "EXPORT_README.txt").write_text(
        "TopoSHAP — ICLR 2027 Overleaf upload\n"
        "=====================================\n\n"
        "Generated by scripts/make_overleaf_export.py; do not edit here,\n"
        "edit paper/ in the repository and re-export.\n\n"
        "Before submission:\n"
        "  1. Replace iclr2027_conference.sty (a placeholder) with the\n"
        "     official ICLR 2027 style file, and add the official .bst.\n"
        "  2. Switch \\bibliographystyle{plainnat} in main.tex to\n"
        "     \\bibliographystyle{iclr2027_conference}.\n"
        "  3. If the official style clashes with natbib, delete the\n"
        "     \\usepackage{natbib} line in preamble.tex (the style loads\n"
        "     its own copy).\n"
        "  4. Review the AI use / reproducibility statements in main.tex.\n"
    )

    # verify every \input target exists in the export
    unresolved = []
    for f in [DEST / "main.tex", *(DEST / "sections").glob("*.tex")]:
        text = re.sub(r"(?<!\\)%.*", "", f.read_text())
        for m in re.finditer(r"\\input\{([^}]+)\}", text):
            t = m.group(1)
            if not ((DEST / f"{t}.tex").exists() or (DEST / t).exists()):
                unresolved.append(f"{f.name}: {t}")
    print(f"exported to {DEST} ({len(figures) - len(missing)} figures)")
    if missing:
        print("figures not yet rendered (placeholder box will show):")
        for m in missing:
            print(f"  {m}")
    if unresolved:
        raise SystemExit(f"unresolved \\input targets: {unresolved}")


if __name__ == "__main__":
    main()
