"""Generate the paper's results tables as LaTeX (booktabs).

Reads the assembled summaries (results/fair_table/*.json) plus the
no-ground-truth records, and writes paper/tables/{t1_graph,t2_lifted,
t3_nogt}.tex. Best mean per column is bolded; every entry carries a
multi-seed sd. Pending cells (fleets in flight) render as '--' and are
listed on stderr so an incomplete table is never mistaken for final.

Numbers are never typed by hand: regenerate with
    python scripts/make_paper_tables.py
after scripts/assemble_fair_table.py and assemble_lifted_table.py.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "paper" / "tables"
DATASETS = ["benzene", "fluoride_carbonyl", "mutagenicity_gxai",
            "alkane_carbonyl"]
HEADS = ["Benzene", "FluorideCarbonyl", "Mutagenicity", "AlkaneCarbonyl"]
PENDING: list[str] = []


def cell(mean, sd, bold=False, near=False):
    if mean is None:
        return "--"
    body = f"{mean:.3f} $\\pm$ {sd:.3f}"
    if bold:
        body = f"\\textbf{{{body}}}"
    if near:
        body = "\\cellcolor{black!10}" + body
    return body


def near_mask(cols, best):
    """Cells within one sd (of the best cell) of the best mean."""
    out = []
    for j in range(len(cols[0])):
        b = best[j]
        row = set()
        if b >= 0:
            mb, sb = cols[b][j]
            for i, r in enumerate(cols):
                m = r[j][0]
                if m is not None and abs(m - mb) <= (sb or 0):
                    row.add(i)
        out.append(row)
    return out


def bold_mask(cols):
    """Index of best (max) mean per column, ignoring Nones."""
    out = []
    for j in range(len(cols[0])):
        vals = [(i, r[j][0]) for i, r in enumerate(cols) if r[j][0]
                is not None]
        out.append(max(vals, key=lambda t: t[1])[0] if vals else -1)
    return out


def render(rows, colheads, caption, label, extra_note=""):
    """rows: list of (name, [(mean, sd), ...]). Bold best per column;
    gray-shade cells within one sd (of the best) of the best mean."""
    best = bold_mask([r[1] for r in rows])
    near = near_mask([r[1] for r in rows], best)
    lines = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py -- do not edit",
        "\\begin{table}[t]", "\\centering", "\\small",
        f"\\caption{{{caption}{extra_note}}}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{l" + "c" * len(colheads) + "}",
        "\\toprule",
        " & " + " & ".join(colheads) + " \\\\",
        "\\midrule",
    ]
    for i, (name, vals) in enumerate(rows):
        tds = [cell(m, s, bold=(best[j] == i), near=(i in near[j]))
               for j, (m, s) in enumerate(vals)]
        lines.append(name + " & " + " & ".join(tds) + " \\\\")
        for j, (m, s) in enumerate(vals):
            if m is None:
                PENDING.append(f"{label}: {name} / {colheads[j]}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def t1_graph():
    """Table 1: rank-1 validation on the GraphXAI benchmarks."""
    j = json.loads((REPO / "results" / "fair_table" /
                    "summary.json").read_text())["rows"]

    def best_arch(ds, meth):
        picks = [(j[ds].get(f"{meth}_{a}") or {"mean": None})
                 for a in ("gcn", "gin")]
        picks = [p for p in picks if p["mean"] is not None]
        if not picks:
            return (None, None)
        p = max(picks, key=lambda r: r["mean"])
        return (p["mean"], p["sd"])

    def ours(ds, key):
        r = j[ds].get(key)
        return (r["mean"], r["sd"]) if r else (None, None)

    rows = []
    # our two outputs on the same GNN subjects (from select_gnn files,
    # summarized into summary.json externally? they are not — pull from
    # the raw files instead)
    import glob
    from collections import defaultdict
    exp = {d: j[d]["n"] for d in DATASETS}

    def from_files(pattern_fmt):
        out = []
        for ds in DATASETS:
            per_arch = {}
            for arch in ("gcn", "gin"):
                seeds = defaultdict(dict)
                for f in glob.glob(pattern_fmt.format(ds=ds, arch=arch)):
                    if "_l" in Path(f).name.replace(ds, "DS"):
                        continue
                    d = json.loads(Path(f).read_text())
                    for r in d["records"]:
                        seeds[d["seed"]][r["orig_index"]] = r["gea"]
                ms = [np.nanmean(list(v.values()))
                      for s, v in sorted(seeds.items())
                      if len(v) == exp[ds]]
                if len(ms) == 3:
                    per_arch[arch] = (float(np.mean(ms)),
                                      float(np.std(ms)))
            if per_arch:
                out.append(max(per_arch.values(), key=lambda t: t[0]))
            else:
                out.append((None, None))
        return out

    rows.append((r"\method{} (attribution)", from_files(
        str(REPO / "results/graph_baselines/"
            "gnn_shapley_participation_{ds}_{arch}_s4?*.json"))))
    rows.append((r"\method{} (explanation)", from_files(
        str(REPO / "results/graph_baselines/"
            "select_gnn_{ds}_{arch}_s4?*.json"))))
    for meth, name in (("subgraphx", "SubgraphX"),
                       ("pgexplainer", "PGExplainer"),
                       ("gnnexplainer", "GNNExplainer"),
                       ("random", "Random")):
        rows.append((name, [best_arch(ds, meth) for ds in DATASETS]))
    cap = (r"\textbf{Graph benchmarks (rank-1 validation).} Node-level "
           r"explanation accuracy (GEA, mean $\pm$ sd over 3 training "
           r"seeds) on the full ground-truth-positive test splits. All "
           r"methods explain the same parameter-matched GNN subjects on "
           r"identical splits; per method, the better of the GCN/GIN "
           r"subjects is shown (both in \cref{app:tables}). \method{} "
           r"explanations cost $\sim$0.04\,s per instance vs.\ "
           r"$\sim$20\,s for SubgraphX on identical hardware.")
    return render(rows, HEADS, cap, "tab:graph-benchmarks")


def t1_by_subject():
    """Appendix table: per-subject (GCN/GIN) GEA for every method on the
    GraphXAI benchmarks, plus the zero-fill removal-semantics ablation.
    Backs the two promises pointing at app:tables: Table 1's caption
    (per-method better-subject selection) and the section-5 removal-
    semantics claim."""
    import glob
    from collections import defaultdict

    j = json.loads((REPO / "results" / "fair_table" /
                    "summary.json").read_text())["rows"]
    exp = {d: j[d]["n"] for d in DATASETS}

    def per_arch(pattern_fmt, ds, arch):
        seeds = defaultdict(dict)
        for f in glob.glob(pattern_fmt.format(ds=ds, arch=arch)):
            if "_l" in Path(f).name.replace(ds, "DS"):
                continue
            d = json.loads(Path(f).read_text())
            for r in d["records"]:
                seeds[d["seed"]][r["orig_index"]] = r["gea"]
        ms = [np.nanmean(list(v.values()))
              for s_, v in sorted(seeds.items()) if len(v) == exp[ds]]
        if len(ms) == 3:
            return (float(np.mean(ms)), float(np.std(ms)))
        return (None, None)

    def ours_row(pattern):
        fmt = str(REPO / "results/graph_baselines" / pattern)
        return [per_arch(fmt, ds, arch)
                for ds in DATASETS for arch in ("gcn", "gin")]

    def summary_row(meth):
        out = []
        for ds in DATASETS:
            for arch in ("gcn", "gin"):
                r = j[ds].get(f"{meth}_{arch}")
                out.append((r["mean"], r["sd"]) if r else (None, None))
        return out

    rows = [
        (r"\method{} (attribution)",
         ours_row("gnn_shapley_participation_{ds}_{arch}_s4?*.json")),
        (r"\method{} (explanation)",
         ours_row("select_gnn_{ds}_{arch}_s4?*.json")),
        (r"\method{} (explanation, zero-fill)",
         ours_row("gnn_select_zerofill_{ds}_{arch}_s4?*.json")),
        ("SubgraphX", summary_row("subgraphx")),
        ("PGExplainer", summary_row("pgexplainer")),
        ("GNNExplainer", summary_row("gnnexplainer")),
        ("Random", summary_row("random")),
    ]
    best = bold_mask([r[1] for r in rows])
    near = near_mask([r[1] for r in rows], best)
    disp = {"benzene": "Benzene", "fluoride_carbonyl": "Fluoride",
            "mutagenicity_gxai": "Mutagenicity",
            "alkane_carbonyl": "Alkane"}
    lines = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py -- do not edit",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\caption{\\textbf{Per-subject explanation accuracy.}"
        " Node-level GEA (mean $\\pm$ sd, 3 seeds) for each"
        " parameter-matched GNN subject; \\cref{tab:graph-benchmarks}"
        " reports each method's better subject. The zero-fill row runs"
        " our explanation search with feature zero-filling, SubgraphX's"
        " removal semantics, in place of detachment. Bold marks the best"
        " entry per column; gray marks entries within one sd of it.}",
        "\\label{tab:by-subject}",
        "\\setlength{\\tabcolsep}{3.5pt}",
        "\\resizebox{\\linewidth}{!}{%",
        "\\begin{tabular}{l" + "cc" * len(DATASETS) + "}",
        "\\toprule",
        " & " + " & ".join(
            "\\multicolumn{2}{c}{" + disp[d] + "}" for d in DATASETS)
        + " \\\\",
        "".join(f"\\cmidrule(lr){{{2*i+2}-{2*i+3}}}"
                for i in range(len(DATASETS))),
        "Method & " + " & ".join(["GCN & GIN"] * len(DATASETS))
        + " \\\\",
        "\\midrule",
    ]
    for i, (name, vals) in enumerate(rows):
        tds = [cell(m, s_, bold=(best[jx] == i), near=(i in near[jx]))
               for jx, (m, s_) in enumerate(vals)]
        lines.append(name + " & " + " & ".join(tds) + " \\\\")
        for jx, (m, s_) in enumerate(vals):
            if m is None:
                PENDING.append(f"tab:by-subject: {name} / col{jx}")
    lines += ["\\bottomrule", "\\end{tabular}}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def t2_lifted():
    """Table 2: the structural-lift GCCN subject, both outputs."""
    j = json.loads((REPO / "results" / "fair_table" /
                    "lifted_summary.json").read_text())["rows"]

    def get(ds, karm, key):
        r = j[ds][karm].get(key)
        return (r["mean"], r["sd"]) if r else (None, None)

    rows = [
        (r"attribution, structural lifting",
         [get(ds, "k11s", "attribution_node") for ds in DATASETS]),
        (r"attribution, standard lifting",
         [get(ds, "k11", "attribution_node") for ds in DATASETS]),
        (r"explanation, structural lifting",
         [get(ds, "k11s", "explanation_node") for ds in DATASETS]),
        (r"explanation, standard lifting",
         [get(ds, "k11", "explanation_node") for ds in DATASETS]),
    ]
    acc = [f"{j[ds]['k11s']['accuracy']['mean']:.3f}" for ds in DATASETS]
    ceil = [f"{j[ds]['k11s']['ceiling_share']:.2f}" for ds in DATASETS]
    note = (r" Subject accuracies: " +
            ", ".join(f"{h} {a}" for h, a in zip(HEADS, acc)) +
            r"; alignment-ceiling share $\Pr[v(S^{*})>v(S_{\mathrm{gt}})]$: " +
            ", ".join(f"{h} {c}" for h, c in zip(HEADS, ceil)) + ".")
    cap = (r"\textbf{Lifted topological benchmarks.} Node-projected GEA "
           r"(mean $\pm$ sd, 3 seeds, full populations) for both \method{} "
           r"outputs on the same full-vocabulary GCCN trained under two "
           r"feature liftings. The standard lifting sums boundary features "
           r"into higher-rank cells; the structural lifting uses constant "
           r"features. Bold marks the best entry per column.")
    return render(rows, HEADS, cap, "tab:lifted", extra_note=note)


def t3_nogt():
    """Table 3: faithfulness without ground truth (deletion-AUC)."""
    import glob
    from collections import defaultdict
    ds_list = ["NCI1", "NCI109", "MUTAG", "PROTEINS"]
    agg = {ds: defaultdict(dict) for ds in ds_list}
    # full pre-declared sample = min(50, gt test-split size);
    # MUTAG's whole test split is 47 graphs
    n_targets = {"MUTAG": 47}
    for ds in ds_list:
        for seed in (42, 43, 44):
            recs = {}
            for f in glob.glob(str(
                    REPO / f"results/nogt/{ds}_s{seed}*.json")):
                d = json.loads(Path(f).read_text())
                for r in d["records"]:
                    recs[r["test_pos"]] = r  # offset files merge in
            if len(recs) < n_targets.get(ds, 50):
                continue
            for m in ("toposhap", "occlusion", "gradxinput", "random"):
                aucs = []
                for r in recs.values():
                    sgn = 1.0 if r["v_full"] >= 0 else -1.0
                    c = 1 / (1 + np.exp(
                        -sgn * np.asarray(r["deletion_curves"][m])))
                    aucs.append(float(np.trapz(c, dx=1 / (len(c) - 1))))
                agg[ds][m][seed] = float(np.mean(aucs))
    rows = []
    for m, name in (("toposhap", r"\method{}"), ("occlusion", "Occlusion"),
                    ("gradxinput", r"Gradient$\times$Input"),
                    ("random", "Random")):
        vals = []
        for ds in ds_list:
            v = list(agg[ds][m].values())
            vals.append((float(np.mean(v)), float(np.std(v)))
                        if len(v) == 3 else (None, None))
        rows.append((name, vals))
    # lower is better here: bold the MIN — flip sign trick
    flipped = [(n, [((-m if m is not None else None), s)
                    for m, s in vals]) for n, vals in rows]
    best = bold_mask([r[1] for r in flipped])
    near = near_mask([r[1] for r in flipped], best)
    lines = [
        "% AUTO-GENERATED by scripts/make_paper_tables.py -- do not edit",
        "\\begin{table}[t]", "\\centering", "\\small",
        "\\caption{\\textbf{Faithfulness without ground truth.} "
        "Deletion-AUC (lower is better; predicted-class probability as "
        "cells are detached in score order; mean $\\pm$ sd over 3 "
        "training seeds, 50 pre-declared test complexes each) on "
        "TopoBench datasets with no explanation annotations. Subjects: "
        "full-vocabulary GCCNs over the structural lift; explanations "
        "target the model's own prediction.}",
        "\\label{tab:nogt}",
        "\\begin{tabular}{l" + "c" * len(ds_list) + "}", "\\toprule",
        " & " + " & ".join(ds_list) + " \\\\", "\\midrule",
    ]
    for i, (name, vals) in enumerate(rows):
        tds = [cell(m, s, bold=(best[j] == i), near=(i in near[j]))
               for j, (m, s) in enumerate(vals)]
        lines.append(name + " & " + " & ".join(tds) + " \\\\")
        for jx, (m, s) in enumerate(vals):
            if m is None:
                PENDING.append(f"tab:nogt: {name} / {ds_list[jx]}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.mkdir(exist_ok=True)
    (OUT / "t1_graph.tex").write_text(t1_graph())
    (OUT / "t2_lifted.tex").write_text(t2_lifted())
    (OUT / "t3_nogt.tex").write_text(t3_nogt())
    (OUT / "t1_by_subject.tex").write_text(t1_by_subject())
    print("wrote", OUT / "t1_graph.tex", OUT / "t2_lifted.tex",
          OUT / "t3_nogt.tex")
    if PENDING:
        print("\nPENDING cells (fleets in flight):", file=sys.stderr)
        for p in PENDING:
            print("  " + p, file=sys.stderr)


if __name__ == "__main__":
    main()
